language: C++
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default qt5-qmake qtbase5-dev qtbase5-dev-tools qttools5-dev-tools
script:
  - qmake
  - make
